# Generated by Django 5.0 on 2024-09-01 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, default='null', max_length=254, null=True, unique=True)),
                ('nom', models.CharField(max_length=254)),
                ('prenom', models.CharField(max_length=254)),
                ('postnom', models.CharField(max_length=254)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('adresse', models.CharField(max_length=254)),
                ('sexe', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('specialite', models.CharField(max_length=254)),
                ('photo', models.ImageField(upload_to='profil')),
                ('date_naissance', models.DateField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=254)),
                ('service', models.CharField(max_length=254)),
                ('fonction', models.CharField(max_length=254)),
                ('date_debut', models.DateField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMedecin.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ManyToManyField(through='AppMedecin.Affectation', to='AppMedecin.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=254)),
                ('service', models.CharField(max_length=254)),
                ('fonction', models.CharField(max_length=254)),
                ('date_debut', models.DateField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMedecin.medecin')),
                ('zone_sante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppMedecin.zonesante')),
            ],
        ),
        migrations.AddField(
            model_name='affectation',
            name='zone_sante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppMedecin.zonesante'),
        ),
    ]
