# Generated by Django 5.0 on 2024-09-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedecin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='matricule',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
