# Generated by Django 5.0 on 2024-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedecin', '0002_alter_medecin_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profil'),
        ),
    ]
