# Generated by Django 5.0 on 2024-09-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedecin', '0003_alter_medecin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
