# Generated by Django 5.0 on 2024-09-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedecin', '0004_alter_medecin_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonesante',
            name='designation',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
